



import type { ParsedUtility, PropertyTarget } from './types.js';




export function getCSSProperty(property: PropertyTarget): string {
  const map: Record<PropertyTarget, string> = {
    bg: 'background-color',
    text: 'color',
    border: 'border-color',
    divide: 'border-color',
    ring: '--tw-ring-color',
    placeholder: 'color'
  };
  return map[property];
}




export function escapeClassName(className: string): string {
  return className.replace(/[/:]/g, '\\$&');
}









export function generatePairingCSS(parsed: ParsedUtility): string {
  const cssProperty = getCSSProperty(parsed.property);
  const escapedClass = escapeClassName(parsed.className);
  const lightVar = `--color-${parsed.scale}-${parsed.lightShade}`;
  const darkVar = `--color-${parsed.scale}-${parsed.darkShade}`;

  let css = '';

  
  if (parsed.property === 'placeholder') {
    if (parsed.hasOpacity) {
      css += `.${escapedClass}::placeholder {
  ${cssProperty}: color-mix(in oklch, var(${lightVar}) ${(parsed.opacity! * 100).toFixed(0)}%, transparent);
}
.dark .${escapedClass}::placeholder {
  ${cssProperty}: color-mix(in oklch, var(${darkVar}) ${(parsed.opacity! * 100).toFixed(0)}%, transparent);
}
`;
    } else {
      css += `.${escapedClass}::placeholder {
  ${cssProperty}: var(${lightVar});
}
.dark .${escapedClass}::placeholder {
  ${cssProperty}: var(${darkVar});
}
`;
    }
    return css;
  }

  
  if (parsed.property === 'divide') {
    if (parsed.hasOpacity) {
      css += `.${escapedClass} > :not([hidden]) ~ :not([hidden]) {
  ${cssProperty}: color-mix(in oklch, var(${lightVar}) ${(parsed.opacity! * 100).toFixed(0)}%, transparent);
}
.dark .${escapedClass} > :not([hidden]) ~ :not([hidden]) {
  ${cssProperty}: color-mix(in oklch, var(${darkVar}) ${(parsed.opacity! * 100).toFixed(0)}%, transparent);
}
`;
    } else {
      css += `.${escapedClass} > :not([hidden]) ~ :not([hidden]) {
  ${cssProperty}: var(${lightVar});
}
.dark .${escapedClass} > :not([hidden]) ~ :not([hidden]) {
  ${cssProperty}: var(${darkVar});
}
`;
    }
    return css;
  }

  
  if (parsed.hasOpacity) {
    css += `.${escapedClass} {
  ${cssProperty}: color-mix(in oklch, var(${lightVar}) ${(parsed.opacity! * 100).toFixed(0)}%, transparent);
}
.dark .${escapedClass} {
  ${cssProperty}: color-mix(in oklch, var(${darkVar}) ${(parsed.opacity! * 100).toFixed(0)}%, transparent);
}
`;
  } else {
    css += `.${escapedClass} {
  ${cssProperty}: var(${lightVar});
}
.dark .${escapedClass} {
  ${cssProperty}: var(${darkVar});
}
`;
  }

  return css;
}





export function generateSeparateCSS(parsed: ParsedUtility, darkMode: boolean): string {
  const cssProperty = getCSSProperty(parsed.property);
  const lightVar = `--color-${parsed.scale}-${parsed.lightShade}`;
  const darkVar = `--color-${parsed.scale}-${parsed.darkShade}`;
  const escapedClass = escapeClassName(parsed.className);

  let css = '';

  
  if (parsed.hasOpacity) {
    css += `.${escapedClass} {
  ${cssProperty}: color-mix(in oklch, var(${lightVar}) ${(parsed.opacity! * 100).toFixed(0)}%, transparent);
}
`;
  } else {
    css += `.${escapedClass} {
  ${cssProperty}: var(${lightVar});
}
`;
  }

  
  if (darkMode) {
    if (parsed.hasOpacity) {
      css += `.dark .${escapedClass} {
  ${cssProperty}: color-mix(in oklch, var(${darkVar}) ${(parsed.opacity! * 100).toFixed(0)}%, transparent);
}
`;
    } else {
      css += `.dark .${escapedClass} {
  ${cssProperty}: var(${darkVar});
}
`;
    }
  }

  return css;
}




export function generateCSSModule(
  extractedClasses: Map<string, ParsedUtility>,
  usePairingTokens: boolean,
  darkMode: boolean
): string {
  let css = `/**
 * Skeleton Color Utilities - Auto-generated
 * Generated: ${new Date().toISOString()}
 * Classes: ${extractedClasses.size}
 *
 * This file is generated by @tinyland/vite-plugin-skeleton-colors.
 * It maps Tailwind-style utility classes (bg-surface-100-800) to
 * Skeleton color-pairing CSS custom properties (--color-surface-100-900).
 */

`;

  
  const sortedClasses = [...extractedClasses.entries()].sort((a, b) =>
    a[0].localeCompare(b[0])
  );

  
  for (const [, parsed] of sortedClasses) {
    if (usePairingTokens) {
      css += generatePairingCSS(parsed);
    } else {
      css += generateSeparateCSS(parsed, darkMode);
    }
    css += '\n';
  }

  return css;
}
